#!/bin/bash
# Copyright (c) 2023 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#####################################################################
# Script to validate that Distronode and Distronode Runner are installed.
#
# Usage: check_distronode <PYCMD>
#
# Options:
#     PYCMD - The path to the python executable to use.
#####################################################################

set -x

PYCMD=$1

if [ -z "$PYCMD" ]
then
    echo "Usage: check_distronode <PYCMD>"
    exit 1
fi

if [ ! -x "$PYCMD" ]
then
    echo "$PYCMD is not an executable"
    exit 1
fi

distronode --version

if [ $? -ne 0 ]
then
    cat<<EOF
**********************************************************************
ERROR - Missing Distronode installation

  An Distronode installation cannot be found in the final builder image.

  Distronode must be installed in the final image. If you are using a
  recent enough version of the execution environment file, you may
  use the 'dependencies.distronode_core' configuration option to install
  Distronode for you, or use 'additional_build_steps' to manually do
  this yourself. Alternatively, use a base image with Distronode already
  installed.
**********************************************************************
EOF
    exit 1
fi

distronode-runner --version

if [ $? -ne 0 ]
then
    cat<<EOF
**********************************************************************
ERROR - Missing Distronode Runner installation

  An Distronode Runner installation cannot be found in the final builder
  image.

  Distronode Runner must be installed in the final image. If you are
  using a recent enough version of the execution environment file, you
  may use the 'dependencies.distronode_runner' configuration option to
  install Distronode Runner for you, or use 'additional_build_steps' to
  manually do this yourself. Alternatively, use a base image with
  Distronode Runner already installed.
**********************************************************************
EOF
    exit 1
fi

$PYCMD -c 'import distronode ; import distronode_runner'

if [ $? -ne 0 ]
then
    cat<<EOF
**********************************************************************
ERROR - Missing Distronode or Distronode Runner for selected Python

  An Distronode and/or Distronode Runner installation cannot be found in
  the final builder image using the following Python interpreter:

    $PYCMD

  Distronode and Distronode Runner must be installed in the final image and
  available to the selected Python interpreter. If you are using a
  recent enough version of the execution environment file, you may use
  the 'dependencies.distronode_core' configuration option to install
  Distronode and the 'dependencies.distronode_runner' configuration option
  to install Distronode Runner. You can also use 'additional_build_steps'
  to manually do this yourself. Alternatively, use a base image with
  Distronode and Distronode Runner already installed.
**********************************************************************
EOF
    exit 1
fi
exit 0
