---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream8  # vanilla image!
    # name: quay.io/centos/centos:stream9  # vanilla image!
    # name: registry.fedoraproject.org/fedora:38  # vanilla image!
    # name: registry.access.redhat.com/ubi9/ubi:latest  # vanilla image!

options:
  user: '1000'  # (optional) sets the username or UID
  # tags:  # (optional) sets tags
  #   - 'ee_development:latest'

dependencies:
  python_interpreter:
    package_system: python39  # (optional) name of a Python interpreter OS package to install
    python_path: /usr/bin/python3.9  # (optional) path to the Python interpreter to use

  distronode_core:  # (optional) install distronode-core if the base image doesn't already contain it
    package_pip: https://github.com/distronode/distronode/archive/refs/tags/v2.13.2.tar.gz   # install from a GH ref tarball

  distronode_runner:  # (optional) install distronode-runner if the base image doesn't already contain it
    package_pip: distronode-runner==2.2.1   # install specific version from PyPI

  # lists of Distronode collections and/or roles to install (or the filename of an Distronode Galaxy CLI requirements YAML file)

  # the contents of this key are not validated by distronode-builder itself; they will be written to `requirements.yml` in
  # the root of the generated build context and consumed directly by the distronode-galaxy CLI during the build
  galaxy:
    collections:
    - distronode.windows  # base windows support
    - community.windows  # community windows additions
    - distronode.utils

  # explicit list of Python dependencies to install (in addition to those declared by the collections above)
  python:
  - pywinrm

  # explicit list of bindep entries for OS packages to install (in addition to those declared by the collections above)
  system:
  - iputils [platform:rpm]
